'mysql' => [
    'driver' => 'mysql',
    'url' => env('DATABASE_URL'),
    'host' => env('MYSQLHOST', env('DB_HOST', '127.0.0.1')),
    'port' => env('MYSQLPORT', env('DB_PORT', '3306')),
    'database' => env('MYSQLDATABASE', env('DB_DATABASE', 'laravel')),
    'username' => env('MYSQLUSER', env('DB_USERNAME', 'root')),
    'password' => env('MYSQLPASSWORD', env('DB_PASSWORD', '')),
    'unix_socket' => env('DB_SOCKET', ''),
    'charset' => env('DB_CHARSET', 'utf8mb4'),
    'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
    'prefix' => '',
    'prefix_indexes' => true,
    'strict' => true,
    'engine' => null,
    'options' => extension_loaded('pdo_mysql') ? array_filter([
        PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
    ]) : [],
],